### ISSUE TITLE
What to do to get the FileMon demo to log activity

### ISSUE THREAD

**Issue by Ciceroids** [EasyHook/EasyHook#69]
Hi, I'm a complete newbie to hooking and have just downloaded the latest build of EasyHook (2.7.5870.0) to get me started. Running the FileMon demo on Windows 10 64 bit with a 32 bit app as target, I get the following confirmation message in my log file:

Injected to process 585368
<Press any key to exit>
FileMon has been installed in target 585368.

The target is a language vocabulary tester which can create and open vocab files. Once the above message was received, a few files were opened and edited and a new file created and saved using the target. Nothing more was added to the log file. What do I need to do to get the file access info written to the log file?

Any help will be much appreciated.

**Comment by rlc5m8** [comment]
What command line did you use to execute FileMon?

585368 seems far to be a valid PID.

**Comment by Ciceroids** [comment]
The PID for the target was obtained using the WinGet 
<https://autohotkey.com/docs/commands/WinGet.htm> command in Autohotkey. 
The same command consistently returned 5460 as the PID for File Explorer 
during the same session. I have used AHK's WinGet command on many 
occasions to retrieve process IDs and have no reason to doubt the 
validity of the returned PID in this case. IN any event, FileMon 
confirmed that the code had been validly injected.

The retrieved PID was manually typed into the Windows command prompt 
(cmd) but not run specifically as administrator. I wished to use FileMon 
successfully with cmd before running the FileMon executable from within 
an AHK script (this has failed so far).

Is there any other command prompt I should be using and can FileMon be 
run from within other code, such as an AHK script?

**Comment by rlc5m8** [comment]
> The same command consistently returned 5460 as the PID for File Explorer during the same session. I have used AHK's WinGet command on many occasions to retrieve process IDs and have no reason to doubt the validity of the returned PID in this case.

Fair enough, the ID just seemed large to me. The largest PID I have on my development system is 13320 so I thought it might be off.

> The retrieved PID was manually typed into the Windows command prompt (cmd) but not run specifically as administrator. I wished to use FileMon successfully with cmd before running the FileMon executable from within an AHK script (this has failed so far).

Try letting FileMon start the program e.g.
FileMon "C:/Windows/Syswow64/Notepad.exe" > C:/Log.txt

Replace the path in ""'s with your path. If the RemoteHooking.Inject method is causing problems then maybe RemoteHooking.CreateAndInject will yield better results.

**Comment by rlc5m8** [comment]
As far as AHK goes:

#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

Run,cmd /c FileMon C:/Windows/SYSWOW64/Notepad.exe > log.txt,,Hide

That launches FileMon using a hidden command prompt and dumps the output to a log file. If you want to get the output in another program you'll likely want to use a pipe though parsing isn't totally out of the question either.

**Comment by Ciceroids** [comment]
Many thanks. That worked. However, my project requires hooking re target 
apps which are already running.

Since starting Notepad with FileMon caused the hook to work fine, I 
retrieved the PID for Notepad and used that instead of the Notepad path. 
I got the following error in the log file:

There was an error while connecting to target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in 
injected C++ completion routine. (Code: 15)
    at EasyHook.NativeAPI.Force(Int32 InErrorCode)
    at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 
InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String 
InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, 
Boolean InCanCreateService, Boolean InRequireStrongName, Object[] 
InPassThruArgs)
    at FileMon.Program.Main(String[] args)

I kept getting a similar error when using File Explorer as the target 
app. Is there a known problem with using FileMon or EasyHook itself with 
64 bit apps wen using PIDs?

**Comment by rlc5m8** [comment]
Welcome to my world.
https://github.com/EasyHook/EasyHook/issues/70

It seems there's something wrong with EasyHook and 64-bit programs. I'm willing to bet that if you explicitly start C:/Windows/SYSWOW64/Notepad.exe that you'll be able to attach fine (That's the 32-Bit version).

**Comment by Ciceroids** [comment]
That's very helpful of you, thanks. I was just using 'Run FileMon ...' 
which probably explains the earlier failure.

**Comment by rlc5m8** [comment]
Not a problem, let's hope Issue #70 can get resolved so that we can inject into 64-bit processes.

Nothing like have a fully functional hook and not being able to connect to the process you need.

**Comment by Ciceroids** [comment]
Ah, right. So there is a problem with 64 bit hooking although you can 
hook a 64 bit app if you start it with FileMon or similar injecting 
code. If hooking 64 bit apps works when you start the target yourself 
but not if you just provide the PID of a running app, does this suggest 
that there is a threading issue?

**Comment by rlc5m8** [comment]
> Ah, right. So there is a problem with 64 bit hooking although you can hook a 64 bit app if you start it with FileMon or similar injecting code. If hooking 64 bit apps works when you start the target yourself but not if you just provide the PID of a running app, does this suggest that there is a threading issue?

Are you able to inject into 64-bit processes you start? Regardless of whether or not Filemon starts them I'm unable to hook.

C:\Users\Basic\Downloads\EasyHook>filemon "C:\Windows\notepad.exe"
There was an error while connecting to target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
   at EasyHook.RemoteHooking.CreateAndInject(String InEXEPath, String InCommandLine, Int32 InProcessCreationFlags, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Int32& OutProcessId, Object[] InPassThruArgs)
   at FileMon.Program.Main(String[] args)
<Press any key to exit>

C:\Users\Basic\Downloads\EasyHook>filemon 14064
There was an error while connecting to target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at FileMon.Program.Main(String[] args)
<Press any key to exit>

**Comment by Ciceroids** [comment]
It worked for me, at least with Notepad 64 using the
FileMon "C:/Windows/Syswow64/Notepad.exe" > C:/Log.txt
suggested earlier.

**Comment by rlc5m8** [comment]
> It worked for me, at least with Notepad 64 using the FileMon "C:/Windows/Syswow64/Notepad.exe" > C:/Log.txt suggested earlier.

That's the 32-Bit version of notepad. 64-bit is at C:/Windows/Notepad.exe

**Comment by Ciceroids** [comment]
Silly me. I really do need all the help I can get!

**Comment by Ciceroids** [comment]
In summary, I have encountered two problems:

1. inability to hook 64 bit targets (Issue 70)
2. PID as an argument with FileMon produces no output although the 
injection is confirmed.

I look forward to resolution of these key issues.

**Comment by rlc5m8** [comment]
Fortunately someone's looking into the 64 bit issue tomorrow.

**Comment by spazzarama** [comment]
@Ciceroids @rlc5m8 after downloading the release binaries from GitHub I was successfully able to run NetFX4.0\filemon.exe and inject into both 32-bit and 64-bit processes on 64-bit Windows 10.

I used both the command line and the prompt, both worked fine using either PID or executable path.

Is there anything else you can think of that you are doing that might be different?

Also can you please test ProcessMonitor.exe (GUI logging same stuff as filemon.exe) and ComplexParameterTest.exe (prompt for PID just tests injection, no logs etc).

**Comment by rlc5m8** [comment]
Rebuilding the solution worked for me. Can confirm that files were unblocked, I saw that solution in many of your other posts prior to starting my own issue.

**Comment by Ciceroids** [comment]
Tests on 32 bit targets all passed perfectly running FileMon, 
ProcessMonitor and ComplexParameterTest. Where appropriate, both 
executable path and PID methods all worked. All tests ran running the 
utilities from within an Autohotkey script.

Every attempt to inject into 64 bit apps failed. As there seems to be a 
general understanding in this forum that 64 bit hooking is failing, it 
is interesting that anyone is able to get FileMon etc. to work on 64 bit 
targets.

**Comment by spazzarama** [comment]
@ciceroids 64-bit is now working for @rlc5m8, the issue was that because he was rebuilding only a portion of the easyhook solution there was an assembly version mismatch.

So your issue is something else I think.

Can you please confirm you are using the downloaded binaries without any changes?

**Comment by Ciceroids** [comment]
No rebuilding. Just ran the exe files right out of the box.

**Comment by spazzarama** [comment]
@Ciceroids 

> In summary, I have encountered two problems:
>
> 1. inability to hook 64 bit targets (Issue 70)
> 2. PID as an argument with FileMon produces no output although the
> injection is confirmed.
> 
> I look forward to resolution of these key issues.

Regarding point 2, have you tried using the PID of a notepad 64-bit instance? I don't know anything about how the vocabulary tester is accessing its files, so lets start with something simpler. From your first post it successfully hooked into a 64-bit process, so that is not the issue. 

Could you please follow these steps and then report back:
1. run filemon.exe
2. start notepad.exe (64bit)
3. get the PID of notepad.exe (Task Manager -> Details tab or whatever)
4. use this PID in filemon
5. choose File -> Open in notepad
6. you should see output in filemon command window

**Comment by Ciceroids** [comment]
As per one of my posts yesterday, I no longer have a problem with usig 
the PID as a parameter. My initial problem arose from the omission of a 
switch from the command line in an Autohotkey script.

I have never been able to hook into a 64 bit application. The vocabulary 
tester app is 32 bit. As reported yesterday, all attempts to inject into 
Notepad 64 using both executable path and PID failed.

Thus, my only remaining problem is injecting into 64 bit apps.

**Comment by spazzarama** [comment]
Ah ok, sorry I misread.

I now see your report of the Code 15 error occurring during injection.

From the binary download are you using the .NET 3.5 or .NET 4.0 binaries? Not that it really matter both are working for me without error.

**Comment by spazzarama** [comment]
Just for a sanity check, can you please ensure that all the binaries are "unblocked" if you downloaded using IE.

**Comment by Ciceroids** [comment]
Everything was downloaded using Firefox. No issues reported during download.

**Comment by spazzarama** [comment]
Might have to resort to getting the source, building and debugging sorry (would need to attach to target).

**Comment by Ciceroids** [comment]
> Might have to resort to getting the source, building and debugging 
> sorry (would need to attach to target).
>
>

I assume this will be done by those who develop EasyHook? Since there is 
an apparent problem in hooking to 64 bit targets, EasyHook and its 
examples should be fixed at source to provide 64 bit functionality for 
everyone. Is this work being undertaken?

**Comment by spazzarama** [comment]
@Ciceroids there isn't a problem with hooking 64-bit targets in general. The issue that @rlc5m8 had was a problem at his/her end.

Obviously you are having an issue but if I can't reproduce it here, I can't fix it.

**Comment by Ciceroids** [comment]
Oh, so you are not getting errors when using the downloaded FileMon 
binary to hook into Notepad 64?

**Comment by spazzarama** [comment]
Correct, the binary release works here for 64-bit notepad.
>
>

**Comment by Ciceroids** [comment]
OK, what about version of Windows? Mine is Win 10 - what's yours?

**Comment by spazzarama** [comment]
Windows 10 64-bit also.

**Comment by Ciceroids** [comment]
Do the 'injection failed' logs posted earlier in this thread offer any 
idea of what might be going on or do you think that debugging has to be 
done on individual machines and reported back?

**Comment by rlc5m8** [comment]
Since I'm still getting notifications I thought I'd come back and let everyone know.

I have since reinstalled windows (I was having other issues as well) and the downloaded binaries now work just fine, I think my run times may have been partially broken.

The usual process of Download Binaries -> Right Click -> Properties -> "Unblock" is now enough on it's own and I don't have to build the binaries from source (Though I think I will continue to do so).

**Comment by rlc5m8** [comment]
I'll add that after getting the issues resolved EasyHook worked flawlessly and I've received no complaints from anyone using the application.

**Comment by spazzarama** [comment]
> Do the 'injection failed' logs posted earlier in this thread offer any
> idea of what might be going on or do you think that debugging has to be
> done on individual machines and reported back?

They do narrow it down to either while trying to inject EasyLoad64.dll or while EasyLoad is trying to load the EasyHook .NET assembly or the FileMonInject assembly. Why these are loading could be a range of things, using the fuslogvw.exe to log the .NET assembly binding process can help rule out some things.

**Comment by heavenevil** [comment]
I got exactly the same error, win7sp1 64bit, VS2012, any ideas?

**Comment by asulwer** [comment]
make sure all assemblies that the app requires are located in the same directory.  that error is "improperly" stating you are missing assemblies or they cannot be found.  the solution is not setup properly to build everything into one directory!

adding all assemblies built to the same dir as exe this issue went away for me.

**Comment by QGB** [comment]
@asulwer   i put these in one directory, And `Set-ExecutionPolicy Unrestricted` . And run as admin. But `STATUS_INTERNAL_ERROR`  is still occurring .
![image](https://user-images.githubusercontent.com/8005654/112595893-02c12780-8e46-11eb-9a09-1a33c08aeb6f.png)
